---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-test-screts
  namespace: webslab
spec:
  encryptedData:
    email: AgCNGEx0S9QmFRxAPSD8LtzneUN77SLI0Es1w74vm4oKtf5sf+4yV6qkLGn7GI0xztGU9xUYXfiqHofQsCX3Mr7mqj7IHX7JBrAjIzUAsuzEJiqHWA8iyYtpMKoz8S/g9/cUI7xKxrjJRlzYlgfKLEuLCpev9/EIY/HXu+Qbm36hKODmAw+eaEa9xKb1B7LTkgMPjHjYhPx9KQgfKhGUlQqV+qb3dp6qadKHoAwI0M03Uj0zt4RMORmvgWOrqrPkjUMw9Nr0UoUASdB98Fs0aYmjvW9i7Yt5YTm5EeVBCpm2c1ccU3u6zZNPnrAXpPUN65Vc/IE5nmpxnwlsyjHkZZyE+2ck9IfWAx8DzSAMzCbywu5FL3HPww6jbnxJhNFio7jiM0ukyeOS9GZOc7yE6/DZPSM4H1SNGZFD+j0EG/qnwPjA95+INehDKjgcVjpJ0S1o8XxVT024UFMmSXvbMUn4Txb0L63j2KzWkKpO+Sr5HNtQ4EDApxRcrdlmNgpurIL+DOibhLLnRXnamazyWkKw7F6o6W+ukvVfzkU8qa9FE6Yc6W44Y7/11GxKZ5BRNElAgYZR8sX7XGlWCPQULpipNv4MuQ7L5f6bFVMAFGW5llxdN8FpaTbzhKsrr/uCVQZitJaZsCpHTc7fpW32vmZ4U0Tb7jsou3D6j6+E4iMEgapDYizO4h7RRSyhDb6MzS5n72cXirfDVUbZfpft9BKeEbay0t6w
  template:
    metadata:
      creationTimestamp: null
      name: argocd-test-screts
      namespace: webslab
    type: Opaque
