apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 11-service.yaml
  - 12-deployment.yaml
  - 13-ingress.yaml

namespace: argocd-test

secretGenerator:
  - name: secret-1
    literals:
      - issuerEmail=kennycallado@duck.com
